preset: recommended
risky: false
enabled:
  - unalign_double_arrow
disabled:
  - align_double_arrow
finder:
  exclude:
    - "tests"
    - "example"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  contains:
    - "Foo"
  not-contains:
    - "config"
  path:
    - "foo/Stuff"
  not-path:
    - "libraries"
  depth:
    - "< 3"
